# Generated by Django 5.0.3 on 2024-04-22 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_room_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomparticipant',
            name='question_number',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
