# Generated by Django 5.0.3 on 2024-04-22 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_roomparticipant_question_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomparticipant',
            name='question_number',
            field=models.IntegerField(default=0),
        ),
    ]
