# Generated by Django 5.0.3 on 2024-04-23 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_roomparticipant_question_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomparticipant',
            name='remaining_time',
            field=models.IntegerField(default=40),
        ),
    ]
