# Generated by Django 5.0.3 on 2024-04-26 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_roomparticipant_remaining_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time',
            field=models.IntegerField(default=40, verbose_name='Время ответа'),
        ),
        migrations.AddField(
            model_name='question',
            name='tupe',
            field=models.IntegerField(choices=[(1, '1 Вариант ответа'), (2, 'Несколько вариант ответа')], default=1, verbose_name='Тип вопроса'),
        ),
    ]
