# Generated by Django 5.0.3 on 2024-04-26 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_question_time_question_tupe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='tupe',
            new_name='tupe_question',
        ),
    ]
