# Generated by Django 5.0.3 on 2024-05-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_history_delete_roomparticipant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='time',
            field=models.IntegerField(default=20, verbose_name='Время ответа'),
        ),
    ]
