# Generated by Django 5.0.3 on 2024-04-14 12:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('slug', models.SlugField(max_length=20, unique=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'студентская группа',
                'verbose_name_plural': 'студентские группы',
                'db_table': 'student_groups',
            },
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('avatar', models.ImageField(blank=True, default='main/static/img/user-favicon.svg', null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('surname', models.CharField(blank=True, default='', max_length=30, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('course', models.IntegerField(default=1, verbose_name='Курс')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('can_create', models.BooleanField(default=True, verbose_name='Может создавать')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активирован')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Администратор')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='main.studentgroup', verbose_name='Группа')),
            ],
        ),
        migrations.CreateModel(
            name='UserUUID',
            fields=[
                ('UUID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='UUID', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
