# Generated by Django 5.0.3 on 2024-05-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/user-favicon.svg', null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
    ]
